### ISSUE TITLE
SourceLink: Repository instance not found in cache

### ISSUE THREAD

**Issue by maraf** [dotnet/sourcelink#1032]
I'm trying to update SDK in SDK repository and it fails to build with

`
##[error].dotnet\sdk\8.0.100-preview.5.23269.37\Sdks\Microsoft.Build.Tasks.Git\build\Microsoft.Build.Tasks.Git.targets(49,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) SourceLink: Repository instance not found in cache: 'local:D:\a\_work\1\s\.git'
`

- PR https://github.com/dotnet/sdk/pull/32687
- CI run https://dev.azure.com/dnceng-public/public/_build/results?buildId=280989&view=logs&j=fa59fe4e-195c-56fa-189b-58fd241f10dd&t=e0ea3df6-0956-547c-f7b9-9062676d48ed

Is there something that is needed alongside the SDK update? Or is it unexpected failure?

**Comment by tmat** [comment]
I think this issue is gonna be addressed by https://github.com/dotnet/sourcelink/issues/1032.

What I believe is happening is:

- Arcade SDK adds PackageReference to Source Link packages to most projects being built, except for `src\Assets\TestPackages\dotnet-new\Microsoft.TemplateEngine.TestTemplates.csproj` because `Directory.Build.props` and `Directory.Build.targets` files in `src\Assets` that do not import Arcade SDK targets. 
- Since `Microsoft.TemplateEngine.TestTemplates.csproj` does not have a Source Link package reference, the SDK loads bundled Source Link.
- This results in Source Link tasks loaded from two different locations: package and the SDK.
- Source Link caches repository information globally for the build. Package-based tasks create and use this cache entry. When `Microsoft.TemplateEngine.TestTemplates.csproj` is built the SDK-based task fails to read the information from the cache because the object in the cache fails to cast to the type loaded from SDK. This exception is currently ignored.
- The task attempts to add a new entry to the cache, but that's a no-op since an entry with the same key is already there.
- The next task executed in the same project assumes the cache entry is available also fails to read the entry and now it reports an error because the cache entry should have been there.

![image](https://github.com/dotnet/sourcelink/assets/41759/eedc99c5-ab63-434d-a369-730ef22509d3)
