### ISSUE TITLE
How to get this to work with a git repository hosted on a file share

### ISSUE THREAD

**Issue by Balkoth** [dotnet/sourcelink#1140]
As Visual Studio 17.8 and .NET8 are pushing this i am wondering how to get this to work. No github, azure devops, no fancy stuff. Just a plain old hosted repository on a file share.

**Comment by tmat** [comment]
Do you clone from the share?

**Comment by Balkoth** [comment]
Yep, clone, pull, push.

**Comment by mistoll** [comment]
I'm using shares for remote repository too.
Using a UNC path as remote gives me the warning:

```
Microsoft.Build.Tasks.Git.targets(25,5): warning : Unable to locate repository with working directory that contains directory '\\SRV\PATH'.
```

Looking at the source code I think this is due to https://github.com/dotnet/sourcelink/blob/cb1d453dae3a0405d8a0d109d18f5d57caf7b20b/src/Microsoft.Build.Tasks.Git/GitOperations.cs#L84 :

```
if (!uri.IsFile)
{
    return uri.AbsoluteUri;
}
```

I don't think that UNC paths are intended to pass here. Propably an UNC path should be threaded like an non-file-uri.
