### ISSUE TITLE
Add proper release and release notes

### ISSUE THREAD

**Issue by Zastai** [dotnet/sourcelink#1145]
Dependabot is suggesting I bump Microsoft.SourceLink.GitHub from 1.1.1 to 8.0.0, linking to this repository.

But there is no 8.0.0 release here, so Dependabot is unable to give any indication of what this leap in version number actually brings.

It looks like the Git sourcelink is now included in the .NET 8 SDK (but for some reason as opt-out rather than opt-in, which seems like a recipe for unexpected build failures).
What is the migration path for a project that explicitly references Microsoft.SourceLink.GitHub 1.1.1 (and wants to remain buildable using a .NET 6 SDK)? Just keep referencing 1.1.1 (letting the SDK pick its included 8.0.0 version, if that's what happens)? Bump to 8.0.0 (in which case the release notes are definitely important to get)? Make the package reference conditional (and if so, on what)?

**Comment by tmat** [comment]
Release https://github.com/dotnet/sourcelink/releases/tag/8.0.0 is now published.

> It looks like the Git sourcelink is now included in the .NET 8 SDK (but for some reason as opt-out rather than opt-in, which seems like a recipe for unexpected build failures).

This is intentional. Source Link has been optional for years now (via referencing the Source Link packages). Having Source Link enabled by default significantly improves the default developer experience for .NET SDK projects. We are aware that upgrading to .NET SDK 8 has the potential for breaking the build in rare cases. We provide settings to opt-out of the default Source Link functionality that can be used to remedy these breaks. We believe that the benefits outweigh the downsides.

> What is the migration path for a project that explicitly references Microsoft.SourceLink.GitHub 1.1.1 (and wants to remain buildable using a .NET 6 SDK)? Just keep referencing 1.1.1 (letting the SDK pick its included 8.0.0 version, if that's what happens)? Bump to 8.0.0 (in which case the release notes are definitely important to get)? Make the package reference conditional (and if so, on what)?

The migration path is to remove all Source Link PackageReferences once you update to .NET SDK 8. They are no longer needed.
