### ISSUE TITLE
STANDARD_CI_REPOSITORY_URL should trigger ContinuousIntegrationBuild=true

### ISSUE THREAD

**Issue by ctaggart** [dotnet/sourcelink#115]
Following up from https://github.com/dotnet/sourcelink/issues/114#issuecomment-403679174, the only way I can get my sourcelink json to be deterministic is if I set `/p:ContinuousIntegrationBuild=true` property myself in the CI scripts. The sourcelink json then looks like this:

``` json
{"documents":{"/_/*":"https://github.ecorp.test/raw/taggac/vsphere-automation-sdk-.net/e154aefe03eec1377b9588da5f32a056e97d4805/*"}}
```

I'd really prefer not having to set that manually. It looks like [Microsoft.Build.StandardCI.props](https://github.com/dotnet/sourcelink/blob/master/src/Microsoft.Build.StandardCI/build/Microsoft.Build.StandardCI.props) does what I want:

```xml
<ContinuousIntegrationBuild Condition="'$(ContinuousIntegrationBuild)' == '' and '$(DesignTimeBuild)' != 'true' and '$(STANDARD_CI_REPOSITORY_URL)' != ''">true</ContinuousIntegrationBuild>
```

Is `Microsoft.Build.StandardCI.props` going to be included `Microsoft.SourceLink.Common` package?

**Comment by tmat** [comment]
The plan is to produce a separate package `Microsoft.Build.StandardCI`, not include it in SourceLink. I have considered including in SourceLink package but the problem is that it might introduce a break in build. Consider the following scenario - you start using SourceLink package in your repo but your CI server does not set STANDARD_CI variables at that point. So the build won't be fully deterministic at that point but your build works fine. In future you update your CI server to the latest version that supports STANDARD_CI variables. If SourceLink package just picked them up automatically it would start producing deterministic paths, which might break build or tests. So I think it's better to be explicit and separate SourceLink feature from Standard CI feature.

**Comment by tmat** [comment]
Unfortunately, deterministic builds is a feature that does not work for all projects. If a project uses `AssemblyVersion(*)` it can't be deterministic. If a project uses `CallerFilePathAttribute` and then processes the path embedded by the compiler switching to deterministic paths might break it.

I'd rather burden developers who care about deterministic builds with adding an extra package or setting a property, then burden all SourceLink users to deal with these potential breaks.

**Comment by ctaggart** [comment]
Makes sense 👍
