### ISSUE TITLE
Add support for Bitbucket Enterprise

### ISSUE THREAD

**Issue by tmat** [dotnet/sourcelink#128]
Package `Microsoft.SourceLink.Bitbucket.Enterprise`.

In order to support on-prem Bitbucket we need a documentation on URL formats it uses for cloning repositories and accessing raw files. Are these the only URL formats? https://github.com/ctaggart/SourceLink/blob/master/SourceLink.Create.CommandLine/BitBucketServerUrlConverter.cs

Is there a difference between Server and Data Center?

**Comment by quasarea** [comment]
In our case it is;
Atlassian Bitbucket v4.5.2  and Atlassian Bitbucket v4.6.1:
https://stash1.company.com/projects/TEAM/repos/component/browse/Jenkinsfile?at=59e28fda4986b1cb2a265893c359490330cac810&raw

**Comment by quasarea** [comment]
we overcome this issue by updating **BuildSourceLinkUrl** method in **GetSOurceLinkUrl.cs**:

    var splits = relativeUrl.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
    if (splits.Length != 3)
        throw new Exception($"Expected three parts (separated by '/') in relativeUrl, but got: {relativeUrl}");

    splits[0] = "projects";
    splits[1] = splits[1].ToUpper() + "/repos";
    splits[2] = splits[2] + $"/browse/*?at={revisionId}&raw";

    relativeUrl = string.Join("/", splits);

    var result = UriUtilities.Combine(contentUri.ToString(), relativeUrl);
    return result;

but then I found https://github.com/ctaggart/SourceLink/issues/361 pointing that SourceLinkUrl can be used to customised url structure

**Comment by Culan** [comment]
But is it possible to use SourceLinkUrl with the dotnet / sourcelink?

I’m in the situation that i can’t use ctaggart / sourcelink because our build server is using ssh to our on prem bitbucket server and dotnet / sourcelink bitbucket package generates wrong URL ( for cloud bitbucket ) and SourceLinkUrl parameter in the csproj doesn’t seem to have any effect.

**Comment by adam-sajdak** [comment]
I was doing some quick research about this entire issue of different urls for Bitbucket Cloud vs Enterprise in specific versions. Right now we have at least three different scenarios:
* Bitbucket Cloud
* Bitbucket Enterprise version prior to 4.7
* Bitbucket Enterprise version 4.7 and above

Implementing **BuildSourceLinkUrl** method for individual scenario is quite simple. 
I would assume that we would like to have just one Microsoft.SourceLink.Bitbucket.Git package that works for all above scenarios? Please correct me if I am wrong.
Then the way to do it would be similar to TFS problem with VirtualDirectory, right? In GetSourceLinkUrl class we simply could set:  
`protected override bool SupportsImplicitHost => false;`
Then in csproj add such config:
` <ItemGroup>
    <SourceLinkBitbucketGitHost Include="bitbucket.org" IsEnterprise="true/false" Version=4.7""/>
  </ItemGroup>`

And then use these settings in **BuildSourceLinkUrl** method the same way Tfs is using VirtualDirectory.

The problem is, as soon as I put 
`protected override bool SupportsImplicitHost => false;`
and I rebuild sourcelink project and try to use Microsoft.SourceLink.Bitbucket.Git package created by me then sourcelink stops to work and when I am trying to use it the warning is displayed:
`Source control information is not available - the generated source link is empty.`

I would like to contribute to sourcelink project but I am kind of stuck right now.

**Comment by tmat** [comment]
@adam-sajdak Thanks for looking into this. Could you send your changes in a PR?

**Comment by adam-sajdak** [comment]
@tmat I finally got time to wrap this up. Here is the pull request:
#246
Actually everything works fine right now and it seems that this package supports both Cloud and Enterprise edition in different versions. Please have a look at it.

**Comment by Lonli-Lokli** [comment]
@adam-sajdak  I think you should sign CLA in pull request first?

I am waiting for this PR to be merged, thanks for it!

**Comment by mitulpatel83** [comment]
Please expedite this PR and the subsequent build. It's exactly what we desperately need.

**Comment by kysel** [comment]
I think that It is now waiting for @adam-sajdak to sign CLA. Hope he'll sign it soon.

**Comment by tmat** [comment]
Implemented by https://github.com/dotnet/sourcelink/pull/246
