### ISSUE TITLE
[Azure DevOps] `sourcelink test` on .nupkg/.pdb returns "url hash does not match"

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/sourcelink#209]
I have a private Azure repository on which I ran a CI to build a NuGet package with `msbuild /t:Pack`.

When I download the package, and `sourcelink test ....nupkg`, I get a lot of 

> error: url hash does not match: eb38eb5d3a7a7daa363d02a65413b12846dd177b

(once per file)

I then tried to build the code locally (code is already pushed) and did `sourcelink test ....pdb` with the same result.

Is there any way I can collect logs of what's going on?

**Comment by tmat** [comment]
You can pass `/bl:log.binlog` on msbuild command line. That will create a [binary log](http://msbuildlog.com/) for the build. 

Do your projects reference [Microsoft.SourceLink.Vsts.Git](https://www.nuget.org/packages/Microsoft.SourceLink.Vsts.Git/1.0.0-beta-63127-02) package?

/cc @ctaggart

**Comment by jeremyVignelles** [comment]
I meant logs for `sourcelink test`. Yes, I do reference this package. the urls are correct, I can paste them in a browser and see the source files

**Comment by jeremyVignelles** [comment]
Oh, well, I have to admit I'm a bit confused : I found many tutorials out there, some about ctaggart/sourcelink, other about this repository.

I didn't know that `sourcelink test` was a legacy thing, I just followed the troubleshooting steps from here : https://www.meziantou.net/2018/07/09/how-to-debug-nuget-packages-using-sourcelink

it might be an authentication issue, because it's a private VSTS repository, but the lack of logs make it hard to find out. I won't probably be able to curl the URL for this reason, I expected the tool to authenticate automatically in some way (like a credential provider for visual studio or from my Windows (azure AD) session).

Are you telling me that `sourcelink test` does not support authentication and that it can be my issue? Would it be possible that the fact that I can't debug in VS is unrelated to that?

**Comment by jeremyVignelles** [comment]
That's it, I debugged dotnet-sourcelink and the `HashUrl` method is redirected to a login page (which ends in 200), but the hash is computed on the login page.

I guess it's expected then, I'll need to see why my VS won't step into my code. I'll see that tomorrow.
Do I need to include the .pdb in my package or is it really optional? How does it resolve the files then?

**Comment by jeremyVignelles** [comment]
Debugging works only if I set

```xml
<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
```

in my package. Is that something expected?

**Comment by ctaggart** [comment]
Yes, it is in the readme: https://github.com/dotnet/sourcelink#using-sourcelink

**Comment by jeremyVignelles** [comment]
It is said to be "Optional", why? If I can't debug without it being set, why is it optional?

**Comment by tmat** [comment]
It is optional since you can use other methods to distribute the PDB, which there are a few.

If you publish your library to NuGet.org it is now recommended to use [.snupkg packages](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) to publish your PDBs. This is a new NuGet feature that has just been released.

You can also publish your PDB to a VSTS symbol server.

**Comment by tmat** [comment]
@jeremyVignelles Does it work for you now, or do you still have issues debugging?

**Comment by jeremyVignelles** [comment]
Sorry, I forgot this thread. Thanks for your answer, embedding the pdb works for me.

**Comment by cmw9706** [comment]
Apologies cause I know this is closed, but I am having the same issue and my csproj is already embedding the PDB files. I am using an Azure DevOps artifact feed so I know I can't use the .snupkg.  The [read me in the sourcelink github](https://github.com/dotnet/sourcelink) seems to suggest this is the appropriate work around for this.  

When I run `sourcelink test` i get `error: url hash does not match:` and I try and curl the url it returns and I get an Azure Devops authentication screen? I can see the source code in a browser just fine.

The only difference about my configuration is I am using nuget pack to create my package? Is there something I need to set up to authenticate in my environment so that I can download the files? Is there another trouble shooting step I am missing? Asking cause I don't know if in this instance you ever got `sourcelink test` to pass. I am also running on VS for mac but get the same issue on windows. Any input would be greatly appreciated.
