### ISSUE TITLE
Enable source link on arm/arm64 processors

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sourcelink#231]
According to https://github.com/dotnet/corefx/pull/34607/files#r248404919, source link is not supported on arm/arm64 chips.

Since the .NET Core SDK works on these processors, it would seem that enabling source link would make sense.

**Comment by bording** [comment]
The reason ARM isn't supported is because LibGit2Sharp is used, and that relies on native libgit2 binaries. We provide x86 and x64 for Windows, mac, and several linux distros, but I'm not even sure what would be involved in getting a native ARM binary built. It would also likely need to be distro-specific as well, since libgit2 has an OpenSSL dependency on linux.

**Comment by tmat** [comment]
@bording Would it make sense to reimplement the parts of LibGit2 that SourceLink in C#? That would solve a lot of issues, but of course it's a quite a bit of work as well.

**Comment by tmat** [comment]
@boarding If we decided to do this (port the code to C#), would it make sense to do so and maintain the port in LibGit2Sharp repo or rather in Source Link repo?

**Comment by bording** [comment]
> @bording Would it make sense to reimplement the parts of LibGit2 that SourceLink uses in C#? That would solve a lot of issues, but of course it's a quite a bit of work as well.

That does seem like a rather large undertaking. You're basically talking about re-implementing some portion of https://github.com/libgit2/libgit2.

If you were to do that, it seems like a shame to keep it just to this repo, since lots of other people could potentially benefit. However, I'm not sure it would make sense for it to be in LibGit2Sharp or not. 

Seems like something that would be worth discussing with the libgit2 maintainers first, though (of which I'm not. I can only claim some level of influence over LibGit2Sharp).

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/sourcelink/pull/288
