### ISSUE TITLE
Source Link on Bitbucket Cloud fails to authenticate MFA with VS2017

### ISSUE THREAD

**Issue by AlexN34** [dotnet/sourcelink#245]
Hi,
I've run into troubles using Source Link on a Bitbucket Cloud multifactor auth account on VS2017 Enterprise 15.9.7.

**Git Credential Manager setup**
This is output for the system version, though Visual Studio uses its' own. As the installer doesn't automatically detect this, I've manually copied `git-askpass.exe`, `git-credential-manager.exe` and `*.dll` (including the one for Bitbucket) so that VS picks this version up.
Filepath: `..\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\libexec\git-core`

Logs below pick up the right version when trying to authenticate with Source Link so I'm assuming that GCM has installed ok.
```
git credential-manager version
Git Credential Manager for Windows version 1.18.4
```

**Expected behavior**
In Visual Studio/Source link, we expect the 'Source link authentication failed' window to close after authentication with a new one detailing the source file I'm attempting to view in Bitbucket. 
In `git.log`, lines after: 
```20:46:45.000007 ...\Common.cs:744       trace: [Main] git-credential-manager (v1.18.4) 'reject'``` 
which deletes credentials shouldn't happen.

**Actual behavior**
Stepping through debugger with Source link gives me an Authentication failure when trying to a view a file on Bitbucket: [here](https://imgur.com/a/e54moYC)
Clicking the link to authenticate brings up the Atlassian UI to login, followed by another popup with a single button to Authorise MFA access.
Clicking this opens a confirmation page in browser for Source Tree with token: [here](https://imgur.com/a/pJ3yptZ)
However, nothing else happens from here (in VS or otherwise) - Authentication failed window stays, and clicking the link again just restarts the process.
The log seems to go wrong after: ```20:46:41.337751 ...\Common.cs:709       trace: [LogEvent] Bitbucket credentials for 'https://bitbucket.org/' successfully retrieved.```

My debug VS options are here: [here](https://imgur.com/a/NthXsxo)

I started the process up to my first screenshot with Auth failure window and cleared the log first, so this trace should reflect what happens during the auth process.

```
20:46:04.927318 ...\Common.cs:744       trace: [Main] git-credential-manager (v1.18.4) 'get'
20:46:04.988317 ...\Git\Where.cs:348    trace: [FindGitInstallations] found 1 Git installation(s).
20:46:04.994318 ...Configuration.cs:222 trace: [LoadGitConfiguration] git All config read, 25 entries.
20:46:04.998318 ...\Common.cs:479       trace: [LoadOperationArguments] interactive = 'true'.
20:46:05.050317 ...\Common.cs:85        trace: [CreateAuthentication] detecting authority type for 'https://bitbucket.org/'.
20:46:05.063317 ...uthentication.cs:313 trace: [GetAuthentication] authentication for Bitbucket created
20:46:05.063317 ...\Common.cs:192       trace: [CreateAuthentication] authority for 'https://bitbucket.org/'  is Bitbucket.
20:46:05.063317 ...\Common.cs:765       trace: [QueryCredentials] querying 'Bitbucket' for credentials.
20:46:05.103316 ...icationPrompts.cs:96 trace: [CredentialModalPrompt] prompting user for credentials.
20:46:33.426772 ...\RestClient.cs:35    trace: [TryGetUser] server responded with Forbidden.
20:46:33.426772 ...\RestClient.cs:55    trace: [TryGetUser] two-factor app authentication code required
20:46:33.427772 ...hAuthenticator.cs:38 trace: [GetAuthAsync] authentication failed
20:46:33.428770 ...cationPrompts.cs:121 trace: [AuthenticationOAuthModalPrompt] prompting user for authentication code.
20:46:37.740215 ...Authenticator.cs:182 trace: [GetAccessToken] server responded with OK.
20:46:37.748189 ...Authenticator.cs:355 trace: [GetAuthenticationResult] authentication success: new personal access token created.
20:46:38.764789 ...\RestClient.cs:35    trace: [TryGetUser] server responded with OK.
20:46:38.764789 ...\RestClient.cs:42    trace: [TryGetUser] authentication success: new password token created.
20:46:38.765777 ...\RestClient.cs:80    trace: [FindUsername] Found username [xxxxxxxxx]
20:46:38.765777 ...\Authority.cs:104    trace: [AcquireToken] Remote username [xxxxxxxxx] != [xxxxxxxxxxx@xxxxxxxx] supplied username
20:46:38.765777 ...uthentication.cs:370 trace: [InteractiveLogon] token acquisition succeeded
20:46:38.767775 ...uthentication.cs:251 trace: [SetCredentials] xxxxxxxxx at https://bitbucket.org/
20:46:38.768773 ...uthentication.cs:251 trace: [SetCredentials] xxxxxxxxx at https://xxxxxxxxx@bitbucket.org/
20:46:38.784776 ...uthentication.cs:251 trace: [SetCredentials] BitbucketRefresh at https://bitbucket.org/refresh_token
20:46:38.784776 ...uthentication.cs:251 trace: [SetCredentials] BitbucketRefresh at https://BitbucketRefresh@bitbucket.org/refresh_token
20:46:38.802775 ...\Authority.cs:214    trace: [ValidateCredentials] authentication type = 'Credential'.
20:46:40.275672 ...\RestClient.cs:35    trace: [TryGetUser] server responded with Unauthorized.
20:46:40.275672 ...\RestClient.cs:61    trace: [TryGetUser] authentication unauthorized
20:46:40.275672 ...\Authority.cs:225    trace: [ValidateCredentials] credential validation failed
20:46:40.275672 ...\Authority.cs:214    trace: [ValidateCredentials] authentication type = 'Token'.
20:46:41.336747 ...\RestClient.cs:35    trace: [TryGetUser] server responded with OK.
20:46:41.336747 ...\RestClient.cs:42    trace: [TryGetUser] authentication success: new password token created.
20:46:41.336747 ...\RestClient.cs:80    trace: [FindUsername] Found username [xxxxxxxx]
20:46:41.336747 ...\Authority.cs:221    trace: [ValidateCredentials] credential validation succeeded
20:46:41.336747 ...\Common.cs:897       trace: [QueryCredentials] credentials for 'https://bitbucket.org/' found.
20:46:41.337751 ...\Common.cs:709       trace: [LogEvent] Bitbucket credentials for 'https://bitbucket.org/' successfully retrieved.
20:46:45.000007 ...\Common.cs:744       trace: [Main] git-credential-manager (v1.18.4) 'reject'
20:46:45.060006 ...\Git\Where.cs:348    trace: [FindGitInstallations] found 1 Git installation(s).
20:46:45.065005 ...Configuration.cs:222 trace: [LoadGitConfiguration] git All config read, 25 entries.
20:46:45.097033 ...\Common.cs:85        trace: [CreateAuthentication] detecting authority type for 'https://bitbucket.org/'.
20:46:45.111007 ...uthentication.cs:313 trace: [GetAuthentication] authentication for Bitbucket created
20:46:45.111007 ...\Common.cs:192       trace: [CreateAuthentication] authority for 'https://bitbucket.org/'  is Bitbucket.
20:46:45.111007 ...\Common.cs:273       trace: [DeleteCredentials] deleting Bitbucket credentials for 'https://bitbucket.org/'.
20:46:45.114008 ...Authentication.cs:99 trace: [DeleteCredentials] Deleting Bitbucket Credentials for https://bitbucket.org/
20:46:45.125007 ...aseSecureStore.cs:68 trace: [Delete] credentials for 'git:https://bitbucket.org' deleted from store.
20:46:45.126008 ...uthentication.cs:106 trace: [DeleteCredentials] host credentials deleted for https://bitbucket.org/
20:46:45.131016 ...aseSecureStore.cs:68 trace: [Delete] credentials for 'git:https://bitbucket.org/refresh_token' deleted from store.
20:46:45.131016 ...uthentication.cs:115 trace: [DeleteCredentials] host refresh credentials deleted for https://bitbucket.org/refresh_token

```
Any guidance on how to proceed from here would be greatly appreciated - thanks in advance!

**Comment by tmat** [comment]
@chuckries

**Comment by chuckries** [comment]
@AlexN34 Thanks for reporting this issue, and for your detailed analysis. I have been able to identify several issues surrounding Bitbucket Auth that we did not originally understand or account for. Below I present the facts that I have been able to come up with. Unfortunately I have not found a direct workaround, but I have come up with some issues that we should be able to fix in order to unblock this.

## Facts
1. Source Link in VS uses HTTP Basic Auth for HTTPS URL's only. OAuth is supported for Azure Dev Ops using VS's internal keychain. For all other providers we piggy back on GCM to get basic auth credentials, as you've seen.
2. The dotnet/sourcelink package provided for Bitbucket creates Source Link URL's in the format `https://bitbucket.org/{account}/{repo}/raw/{revision}/*`. These are website URL's, not REST API Url's. I will show later how this is getting in our way. We probably want to be using Bitbucket REST API Url's, in the form `https://api.bitbucket.org/2.0/repositories/{account}/{repository}/src/{revision}/*`
3. Enabling 2FA disables HTTP Basic Auth for both the Bitbucket website and the REST API. This is really the heart of the issue. When 2FA is enabled and we go to GCM for credentials, the username/password returned to us is actually an OAuth 2.0 Bearer token. We send this token as a Basic auth token, which does not work. (Note: This works for git clone authentication because BitBucket explicitly accepts an OAuth token for git clone, likely to support this scenario).
4. Bitbucket allows for the creation of "Application Passwords" to allow Basic Auth flows when 2FA is enabled. These don't work currently for Source Link though; Application Passwords cannot be used to access the Bitbucket website, and since we are generating website Url's as opposed to REST API Url's, these will not work.
5. Even if we do use REST API Url's, VS will pass "api.bitbucket.org" into GCM when it should pass "bitbucket.org" in order to function properly. 

So at the end of all of this, the answer is that with 2FA enabled, you need to create and use an Application Password. However, due to other issues, that Application Password will not yet work with VS Source Link.

In a test environment, I was able to get Source Link to access a Bitbucket private repo file through a REST API Url using an Application Password, so it is possible. Unfortunately these issues cannot all be worked around at the same time in VS 2017. 

**Also: Disabling 2FA will cause everything to work correctly, but I understand this is far from an ideal workaround.**

@tomat I will log a separate bug, but I think we need to update the BitBucket sourcelink package to generate REST API Url's and do some testing around that. I will also log bugs on the VS side to account for GCM integration with respect to 2FA in BitBucket. 

References:
[OAuth On Bitbucket Cloud](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html)
[App Passwords](https://confluence.atlassian.com/bitbucket/app-passwords-828781300.html)
[GCM on Bitbucket Auth](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/blob/master/Docs/Bitbucket.md)

**Comment by tmat** [comment]
@chuckries Thanks for these insights.

**Comment by chuckries** [comment]
@tmat @AlexN34 Based on my testing I believe Bitbucket with 2FA will work in VS 2017 with:
1. An updated dotnet/sourcelink package for Bitbucket that produces REST API Url's and 
2. The 'fallback to GCM Auth' debugger option enabled. Without this the debugger will not go to GCM for the api.bitbucket.org url. 

My fear in switching to REST API Urls for bitbucket is breaking other scenarios like public repo access or non 2FA scenarios. Additionally, in my testing, an auth error against the REST API returns 403 FORBIDDEN instead of 401 UNAUTHORIZED. This is to prevent a data leak of private repo contents (for example, GitHub returns 404 in the same scenario), but the VS Debugger will not handle it correctly.

**Comment by AlexN34** [comment]
Thanks for looking into this and the summary @chuckries - I had also tried app passwords with the same result so definitely appreciate the explanation and current options, even if not ideal.

**Comment by chuckries** [comment]
@AlexN34 I looked into this a bit more while working on new Source Link Auth support. There is a basic issue we are running into with GCM and MFA for BitBucket. We have always expected GCM to return creds that will work with HTTP Basic Authentication. This is true for GitHub, non-MFA BitBucket, and others. For BitBucket MFA, however, the credentials return from GCM represent an OAuth Bearer token. BitBucket allows this bearer token to be used for git clone (probably to directly support the GCM scenario), but it doesn't accept it in a Basic auth HTTP header. Since GCM is a black box to VS, we have no way to know whether or not MFA is in use and whether or not the credentials returned reprense Basic or Bearer. 

We may be able to workaround this, like sending multiple request for BitBucket in the case that one type of auth fails. Unfortunately app passwords do not work here because the app password credential itself will never be returned from GCM. I need to continue investigating but I am going to be out on vacation for a few weeks.

**Comment by JonCubed** [comment]
@chuckries is there any update on your investigation of this?

**Comment by JonCubed** [comment]
@chuckries I noticed that #447 got merged any chance we can get it pushed to nightly or nuget.org  to take it for a run?

**Comment by chuckries** [comment]
@tmat how can I push out new packages to nuget?

@JonCubed Unfortunately the new Source Link package is not enough, their are VS side changes that are required to support the 2FA workflow as well. Those changes will be in an upcoming VS preview, I plan to update this thread and ask the community to try it out once that is available.

**Comment by tmat** [comment]
New packages will be available today on [MyGet](https://dotnet.myget.org/Gallery/sourcelink).

**Comment by JonCubed** [comment]
thanks @tmat 

@chuckries thanks for getting this done, is there an issue I can follow on VS side?

**Comment by tmat** [comment]
Package version 1.0.0-beta2-19554-01 has been published to NuGet.

**Comment by pogonica** [comment]
Added an item also on VS side
https://developercommunity.visualstudio.com/content/problem/852811/unable-to-use-sourcelink-on-bitbucket-with-2fa.html
