### ISSUE TITLE
Generated resource files are not included by EmbedUntrackedSources

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/sourcelink#392]
![image](https://user-images.githubusercontent.com/19413848/63794327-a0ddbc00-c8b6-11e9-8b08-348359c9bd6f.png)

Currently, Resx generated files don't get embedded into sourcelink enabled PDBs. Hopefully, sourcelink would populate the embedded files list right before compile to ensure all sources get embedded.  We had to work around this in CoreCLR for sourcelink validation.

**Comment by tmat** [comment]
/cc @nguerrera @jaredpar 

An interesting issue. The problem is that we have potentially arbitrary number of targets that run _before_ `CoreCompile` target that may add new `Compile` items to the compilation. Source Link target that inspects the `Compile` items and determines which are untracked needs to also run before `CoreCompile` but after all these targets. There is however no convention currently available that would allow us to ensure the order.

I see two ways how to solve this:

1) Use `CoreCompileDependsOn` property for ordering

`CoreCompile` depends on targets listed in `$(CoreCompileDependsOn)`. We could introduce a convention that any target that adds a compiler input file must be inserted at the start of `CoreCompileDependsOn` list. Then a target that depends on all compiler inputs being calculated would be appended to the list.

This wouldn't require any changes to the compiler targets files. It would however mean that all custom targets that add compiler inputs need to know about this convention and be updated. Feels error prone.

2) Add `<CallTarget Targets="$(AfterCompilerInputCalculatedTargets)" Condition="$(AfterCompilerInputCalculatedTargets)" />` to `CoreCompile` target. Source Link would then set `AfterCompilerInputCalculatedTargets` to the target that calculates embedded sources based on `Compile` items.

Thoughts?

**Comment by hoyosjs** [comment]
Going forward I have a somewhat strong preference for 2. Guidance on 1 is easy but it's often too brittle and people will see their scenario workarounds as important enough to not follow it, or just never see the guidance because there's a lot of learning in MSBuild by copy-paste.

**Comment by nguerrera** [comment]
+ @rainersigwald

**Comment by rainersigwald** [comment]
`CallTarget` is a horror, but it's the only way to fully guarantee ordering in the face of multiple targets that `BeforeTargets="CoreCompile"`.

The Common.targets convention is to hook code-generation targets to `BeforeCompile`, but of course we can't fix all of the things that didn't do that. We should definitely fix Arcade, though, since folks may look to it for guidance.

**Comment by tmat** [comment]
> The Common.targets convention is to hook code-generation targets to BeforeCompile, but of course we can't fix all of the things that didn't do that.

Let's use this convention then. 

@rainersigwald Is the convention documented somewhere on msbuild docs?

I'll document that in order for `EmbedUntrackedSources` to work the targets need to follow this convention.

**Comment by tmat** [comment]
Fix for Arcade: https://github.com/dotnet/arcade/pull/4062

**Comment by tmat** [comment]
`_SetEmbeddedFilesFromSourceControlManagerUntrackedFiles` target in Source Link needs to have `DependsOnTargets="BeforeCompile"` in order to guarantee that all generators that run before this target also run before `_SetEmbeddedFilesFromSourceControlManagerUntrackedFiles`
