### ISSUE TITLE
The value of SourceRoot.RepositoryUrl with identity is invalid - because of blank?

### ISSUE THREAD

**Issue by izi-ma** [dotnet/sourcelink#410]
Hi, 
I use Microsoft.SourceLink.Vsts.Git version 1.0.0-beta2-19367-01.

When compiling I'm getting error like this:

`packages\microsoft.sourcelink.vsts.git\1.0.0-beta2-19367-01\build\Microsoft.SourceLink.Vsts.Git.targets(36,5): error : The value of SourceRoot.RepositoryUrl with identity 'D:\CBGits\Mg\MyProject\' is invalid: 'http://server:port/tfs/my collection/project/_git/repo'`

I checked the settings described [here](https://github.com/dotnet/sourcelink/issues/162) and it seems to be fine. It is in following form: 

`http://server:port/tfs/my%20collection/project/_git/repo`

Could the blank in the collection name be the reason?

**Comment by izi-ma** [comment]
After some try-outs I found the reason. It is not the blank, but the `project` part in the URL. If I remove it in Settings, it will compile locally. But the problem is that then it is not a valid URL for our repository -the `project` part must be there, otherwise my Push fails.

Any ideas?

**Comment by tmat** [comment]
You're using Microsoft.SourceLink.Vsts.Git package for an on-prem TFS server. This package only works with hosted VSTS service - now known as Azure DevOps Services. You need to use Microsoft.SourceLink.Tfs.Git for TFS server. Note that this package is about to be renamed to Microsoft.SourceLink.AzureDevOpsServer.Git since TFS has been renamed to Azure DevOps Server.
