### ISSUE TITLE
Question about URL format in embedded JSON

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/sourcelink#54]
Does the URL have to be `http://`/`https://`, or can it be `file://`, `ftp://`, etc.?

**Comment by chuckries** [comment]
Today the VS Debugger and VS Code C# Extension Debugger only support http/s URL's. I do not think that file:// URL's would be very interesting to Source Link as the debugger has other ways to find source code by file path. Is ftp:// support something you are looking for?

**Comment by tmat** [comment]
Are the sources under source control? What system (git, TFVC, subversion, ...)?

**Comment by yaakov-h** [comment]
Sources are under TFVC, but I'd rather use local sources if they're already available, instead of hitting the server every time (and by default, prompting).

**Comment by jnm2** [comment]
@yaakov-h The local sources are at the exact same path on every developer's machine?

**Comment by chuckries** [comment]
@yaakov-h There are several ways the debugger will try to find local sources before it will use source link, such that embedding a file:// URI in Source Link would not be necessary. Here are some of the heuristics the debugger will use to find source files locally on disk:
- Locally built binaries: If you build binaries from local source and debug them on the same machine, the debugger will simply find the source at it's absolute path on disk with no configuration required.
- Binaries built on another machine: If the source file cannot be found at its original absolute path, the debugger will search all the project (for a solution) or the opened folder (for File -> Open Folder scenarios) for matching source files. For solutions, the debugger will also search [Debug Source Files](https://msdn.microsoft.com/en-us/library/hdks6de6.aspx) folders, which can be configured through the Solution level properties
- The Open File Dialog and No Source Found page: If the debugger cannot find source anywhere (including not finding it through Source Link), it will prompt the user with a File Open dialog so that you can manually point to the source file on disk. You can optionally choose to add the location of the found source file to the list of directories the debugger will search. If you choose to cancel the File Open dialog, you will be shown the No Source Page which contains diagnostic messages about where the debugger search for source. You can always click the browse hyperlink to search for source again. [No Source Page](https://msdn.microsoft.com/en-us/library/3sehk0fb.aspx)
- Checksum Matching: The debugger always performs a checksum match between the original file (whose checksum is stored in the debug symbol file) and the file we have found on disk by any method above. If the checksum doesn't match, the debugger will not treat the file as the correct source file. If you want to disable this checksum matching behavior and force the debugger to open a file with a matching file name, you can turn it off in Tools -> Options -> Debugging -> Require Source File to Exactly Match the Original Version.

One benefit of Source Link is not requiring your local source code to be checked out at the exact same version/commit to match the source you are debugging. The debugger does not have any way to find source locally on disk that is stored in a version control system at a different commit than what is checked out.
