### ISSUE TITLE
Still confused by the readme

### ISSUE THREAD

**Issue by GeXiaoguo** [dotnet/sourcelink#632]
Maybe it is just me, but when I am going through the read me and trying to set up Source Link for a nuget package I am publishing, I was confused in a few places

> Using Source Link in .NET projects

Is this meant for the publisher or for the consumer of the nuget package. If it is for the publisher, then is there anything the consumer needs to setup? Or is debugging with SourceLink already supported by Visual Studio? 

Source link suppose to link to a repository url and a commit hash. But where do I specify the url and the hash?

**Comment by PathogenDavid** [comment]
> Is this meant for the publisher or for the consumer of the nuget package.

Those instructions are for the publisher.

> If it is for the publisher, then is there anything the consumer needs to setup? Or is debugging with SourceLink already supported by Visual Studio?

SourceLink is already supported by Visual Studio.

If it isn't working, make sure it isn't disabled: Make sure that Tools > Options > Debugging > General > "Enable Source Link support" enabled.

Additionally, for packages which use [separate symbol packages (snupkg)](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg), the NuGet.org Symbol Server must be enabled under Tools > Options >Debugging > Symbols. (For [NuGet packages which directly embed PDBs](https://github.com/dotnet/sourcelink/tree/0815575f4f226973dac0d3b3f9d0229dca8ac4f1#alternative-pdb-distribution), this is not necessary. However I do not recommend that unless you're publishing your packages outside of NuGet.org)

> Source link suppose to link to a repository url and a commit hash. But where do I specify the url and the hash?

It finds them automatically. (That's why there are GitHub-specific, GitLab-specific, etc packages.)

If you want to verify that it found them correctly install the `sourcelink` tool with `dotnet tool install sourcelink --global` and then from your output folder run `sourcelink print-json YourProjectName.pdb`. (You can also run `sourcelink test YourProjectName.pdb`, but that might fail if you have unpushed commits.)

**Comment by GeXiaoguo** [comment]
@PathogenDavid Thanks for the answers.

**Comment by PathogenDavid** [comment]
No problem!
