### ISSUE TITLE
Warning : Source control information is not available - the generated source link is empty.

### ISSUE THREAD

**Issue by btmmf** [dotnet/sourcelink#637]
So I got sourcelink up and running for a nuget package on azure devops (i.e. using git, pipelines and artifacts - all on azure devops).

This took a lot of time and involved a lot of head scratching, including cloning dotnet/sourcelink repository to reverse engineer the meaning of error and warning messages due to their lack of verbosity.

Anyway, I tried to apply the same settings to another solution (on a different azure devops), but I get the following warning from the VS Build Task:

```
==============================================================================
Task         : Visual Studio build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.166.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build
==============================================================================
...
##[warning]C:\Users\tswbuild1\.nuget\packages\microsoft.sourcelink.common\1.0.0\build\Microsoft.SourceLink.Common.targets(52,5): Warning : Source control information is not available - the generated source link is empty.
```

In all my trial and error with the other solution, I never got this warning.
I checked the source code again and from what I can tell, [that log message comes from here](https://github.com/dotnet/sourcelink/blob/dfea1e608dbb3bddb1c02779886c0e6c8a986466/src/SourceLink.Common/GenerateSourceLinkFile.cs#L106). From the logic in the method and given that I do not get any other errors or warnings, I cannot tell what the problem is:

- Is `SourceRoots ` empty?
- Is `root.GetMetadata(Names.SourceRoot.SourceLinkUrl)` null or empty?
- Am I on the wrong track?

**I need help debugging the issue further as I'm stuck here.**

How can I make the log more verbose?
How can I see the values of the internal variables to see what's wrong?

The YML for the VS Build task is the same for both solutions.
There are differences between the solutions obviously, but I don't know which ones are relevant for sourcelink to reproduce the observed behaviour.

**Comment by btmmf** [comment]
The azure solution that's not working has spaces in its name, while the other does not, not sure if this is important or not.

**Comment by petrciml** [comment]
Hi, I have same issue on Azure DevOps Server (on-premise).

My .csproj file:
`<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DebugType>portable</DebugType>
    <PackageId>SourceLinkPoC</PackageId>
    <Version>1.0.5</Version>
    <Authors>XXX YYY</Authors>
    <Company>XXX</Company>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DeterministicSourcePaths Condition="'$(EnableSourceLink)' == ''">false</DeterministicSourcePaths>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat> -->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.AzureDevOpsServer.Git" Version="1.0.0" PrivateAssets="All"/>
  </ItemGroup>
  <ItemGroup>
    <SourceLinkAzureDevOpsServerGitHost Include="devopsserver:8080" VirtualDirectory="tfs"/>
  </ItemGroup>
</Project>`

My YAML build:
`pool:
  name: BuildPool
  workspace:
        clean: all

variables:
  - name: System.PreferGitFromPath
    value: true

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore packages (via DotNet CLI)'
  inputs:
    command: custom
    custom: restore
    arguments: '-s "https://devopsserver:8080/tfs/Collection/_packaging/feed/nuget/v3/index.json"'
    projects: |
      **\*.csproj

- task: DotNetCoreCLI@2
  displayName: 'Build (via DotNet CLI)'
  inputs:
    command: build
    arguments: -v:d /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
    projects: |
      **\*.csproj

- task: PublishSymbols@2
  displayName: 'Publish symbols'
  inputs:
    indexSources: true
    treatNotIndexedAsWarning: true
    publishSymbols: true
    symbolsFolder: '$(Build.SourcesDirectory)'
    searchPattern: '**/bin/**/*.pdb'
    symbolServerType: FileShare
    symbolsPath: '\\shared\dev\app\drop\_symbols'
    detailedLog: true

- task: DotNetCoreCLI@2
  displayName: 'Push packages into feed (via DotNet CLI)'
  inputs:
    command: push
    searchPatternPush: '$(Build.SourcesDirectory)/**/*.nupkg'
    feedPublish: 'test'`

When I build locally, there is no warning and content of the file: "...\obj\Debug\netstandard2.0\SourceLinkPoC.sourcelink.json" is:
`{
    "documents": {
        "/_/*": "https://devopsserver:8080/tfs/Collection/PoC/_apis/git/repositories/SourceLinkPoC/items?api-version=1.0&versionType=commit&version=08a1ffff58cc4a96ca5137ddf5edfe084ed70051&path=/*"
    }
}`

When I build on Azure Pipeline based on YAML file the file .sourcelink.json is empty.
From diagnostic verbose log of the build task:

`1:7>Target "_InitializeAzureDevOpsServerGitSourceLinkUrl" in file "C:\Users\svc.CZ.TFS_BUILD\.nuget\packages\microsoft.sourcelink.azuredevopsserver.git\1.0.0\build\Microsoft.SourceLink.AzureDevOpsServer.Git.targets" from project "D:\BuildAgent1.3\_work\82\s\SourceLinkPoC.csproj" (target "_GenerateSourceLinkFile" depends on it):
       Building target "_InitializeAzureDevOpsServerGitSourceLinkUrl" completely.
       **Output file "|D:\BuildAgent1.3\_work\82\s\|" does not exist.**
       Task "Microsoft.SourceLink.AzureDevOpsServer.Git.GetSourceLinkUrl"
       Done executing task "Microsoft.SourceLink.AzureDevOpsServer.Git.GetSourceLinkUrl".
   1:7>Done building target "_InitializeAzureDevOpsServerGitSourceLinkUrl" in project "SourceLinkPoC.csproj".
   1:7>Target "_GenerateSourceLinkFile" in file "C:\Users\svc.CZ.TFS_BUILD\.nuget\packages\microsoft.sourcelink.common\1.0.0\build\Microsoft.SourceLink.Common.targets" from project "D:\BuildAgent1.3\_work\82\s\SourceLinkPoC.csproj" (target "GenerateSourceLinkFile" depends on it):
       Building target "_GenerateSourceLinkFile" completely.
       **No input files were specified.**
       Using "Microsoft.SourceLink.Common.GenerateSourceLinkFile" task from assembly "C:\Users\svc.CZ.TFS_BUILD\.nuget\packages\microsoft.sourcelink.common\1.0.0\build\..\tools\netcoreapp2.0\Microsoft.SourceLink.Common.dll".
       Task "Microsoft.SourceLink.Common.GenerateSourceLinkFile"
   1:7>C:\Users\svc.CZ.TFS_BUILD\.nuget\packages\microsoft.sourcelink.common\1.0.0\build\Microsoft.SourceLink.Common.targets(52,5): **warning : Source control information is not available - the generated source link is empty.** [D:\BuildAgent1.3\_work\82\s\SourceLinkPoC.csproj]
       Done executing task "Microsoft.SourceLink.Common.GenerateSourceLinkFile".
   1:7>Done building target "_GenerateSourceLinkFile" in project "SourceLinkPoC.csproj".`

I guess that root of the problem is on line:
Output file "|D:\BuildAgent1.3\_work\82\s\|" does not exist.

But I don't know why. This is working folder of the agent (and exists and contain source codes!)

**Comment by tmat** [comment]
@btmmf Any luck resolving the issue? If not could you build with `/bl:log.binlog` and share the `log.binlog` file? When you say your project is on "azure devops" do you mean Azure Repos (cloud-hosted) or an on-prem DevOps server? What SourceLink package do you use?

**Comment by btmmf** [comment]
> @btmmf Any luck resolving the issue?

I don't know. It's a mess, because it's not a complicated problem, but a complex one.

> If not could you build with `/bl:log.binlog` and share the `log.binlog` file? When you say your project is on "azure devops" do you mean Azure Repos (cloud-hosted) or an on-prem DevOps server? What SourceLink package do you use?

See, this is the problem. The overall process involves source code and the buildprocess.
Each of which consists of several different ways of doing things.

We had different combinations of settings and actions (not necessarily only for sourcelink support):
- passing `/p:SourceLinkCreate=true` to the MSBuild that builds the .dll
- having an `EnableSourceLink` property in .csproj
- switching between `Azure Repos` and `DevOps server` package without really knowing which is which (on-prem or cloud) while *also* not really knowing which hosting is actually being used (on-prem or cloud)
- switching to SDK-style .csproj format
- switching to dotnet for everything (build, test, pack ...)

For some of which the error pops-up, but sourcelink actually works.
It is unclear what properties are necessary for which combination of tools, project formats and server setups.

**It would be nice to have one single page that documents all aspects (including peripheral ones) and that is up-to-date.**
At the moment the information is scattered around the internet and it's impossible to know which is up to date.
For something that should be a simple "enabled/disabled" switch, setting up sourcelink was a major PITA.
