### ISSUE TITLE
Visual Studio "gold bar" pop up due to _MicrosoftSourceLinkCommonAssemblyFile

### ISSUE THREAD

**Issue by AArnott** [dotnet/sourcelink#644]
While interacting with my solution, a "gold bar" will sometimes pop up across the top with this:

> The project 'StreamJsonRpc' ran into a problem during the last operation: The result "" of evaluating the value "$(_MicrosoftSourceLinkCommonAssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  C:\Users\andarno\.nuget\packages\microsoft.sourcelink.common\1.0.0\build\InitializeSourceControlInformation.targets You may need to reload the solution after fixing the problem. 

![image](https://user-images.githubusercontent.com/3548/90770614-456ac200-e2af-11ea-86ae-fe1b964a8c6b.png)

**Comment by tmat** [comment]
@davkean Seems like bug in project system not loading props files correctly.

**Comment by davkean** [comment]
This is known. NuGet is writing a bunch of props/targets that we're reloading without coordination. We plan on fixing this by holding off reloading targets until restore has finished //cc @lifengl.

**Comment by davkean** [comment]
Basically being tracked by this: https://github.com/dotnet/project-system/issues/4781.

**Comment by cheenamalhotra** [comment]
Do [microsoft.sourcelink.common](https://www.nuget.org/packages/Microsoft.SourceLink.Common/) and [microsoft.sourcelink.github](https://www.nuget.org/packages/Microsoft.SourceLink.GitHub) NuGet packages support **.NET Standard 2.0**?

We have been building for .NET Standard 2.0 which used to work fine, until we switched to proper multitargeted framework model. Now we're intermittently seeing below error:

`##[error]E:\nuget\microsoft.sourcelink.common\1.0.0\build\InitializeSourceControlInformation.targets(3,81): Error MSB4022: The result "" of evaluating the value "$(_MicrosoftSourceLinkCommonAssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.`

After I removed using this package for .NET Standard targets, error seems suppressed, but too soon to conclude that since it's intermittent.

Just wondering why do these packages not expose a **.NET Standard 2.0** compatible DLL?
Could that be the reason for this issue?
