### ISSUE TITLE
Visual Studio unable to locate git-credential-manager-core for recent git version

### ISSUE THREAD

**Issue by alefranz** [dotnet/sourcelink#862]
SourceLink doesn't seem to work anymore for repository that require authentication.
It seems that recently the git installer has moved the location of `git-credential-manager-core.exe` from `C:\Program Files\Git\mingw64\libexec\git-core` to `C:\Program Files\Git\mingw64\bin` (see https://github.com/GitCredentialManager/git-credential-manager/issues/762).
Visual Studio is no longer able to locate it, even if this folder is in the path.
Installing the standalone `gcm-win` doesn't fix the problem either.

Logs:
```
Navigating to symbol 'XXX()' from 'XXX'.
Symbol found in assembly path 'C:\Users\XXX\.nuget\packages\xxx\n.n.n\lib\netstandard2.1\XXX.dll'
Found embedded PDB file.
git-credential-manager-core.exe: "git-credential-manager-core.exe" could not be found.
ERROR: The request failed with code 404 : "NOT FOUND". Treating 404 as authentication failure. Some services return 404 instead of 401 for authentication failures.
Timed out trying to download source code from SourceLink. Subsequent requests may succeed.
```

**Comment by tmat** [comment]
@chuckries

**Comment by chuckries** [comment]
@KalleOlaviNiemitalo no it does not, it directly invokes the `git-credential-manager-core.exe` that is installed with Visual Studio.

@alefranz this was recently fixed in a few versions of Visual Studio, can you provide the specific version you are seeing this issue in?

**Comment by alefranz** [comment]
ah! I'm on Preview 1 of 17.4.0, I'll wait for the next preview and re-open if it will be still an issue.
Thank you both and have a nice weekend!

**Comment by chuckries** [comment]
@alefranz yes it is known to be broken in preview 1 unfortunately, but will be fixed in preview 2.

If you need to fix in preview 1, you **should** be able to:
1. Close all VS instances
2. Open `<vs install root>\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TeamExplorer.pkgdef` as Administrator in a text editor
3. Change `"GitCredentialManagerCoreExePath"="$PackageFolder$\Git\mingw64\libexec\git-core\git-credential-manager-core.exe"` to `"GitCredentialManagerCoreExePath"="$PackageFolder$\Git\mingw64\bin\git-credential-manager-core.exe"`
4. Open a "Developer Command Prompt for VS 2022 Preview" as Administrator.
5. Run `devenv /setup`
6. Open VS and retry the repro.
